<?xml version="1.0"?>

<!DOCTYPE root [

    <!ELEMENT root (items, data)>
    <!ELEMENT data (damagespecs)>
    <!ELEMENT items (ammo, projectile_weapons, melee_weapons, throwables, bombs, traps, aid_items, other_items)>


    <!-- ************ ELEMENT SECTION ************ -->


    <!ELEMENT projectile_weapons (projectile_weapon*)>
    <!ELEMENT ammo (ammo_type*)>
    <!ELEMENT throwables (throwable*)>
    <!ELEMENT aid_items (aid*)>
    <!ELEMENT melee_weapons (melee_weapon*)>
    <!ELEMENT bombs (bomb*)>
    <!ELEMENT traps (trap*)>
    <!ELEMENT other_items (other_item*)>
    <!ELEMENT damagespecs (damage_spec*)>

    <!ELEMENT projectile_weapon ((RankUnlockCondition|UsageUnlockCondition))>
    <!ELEMENT ammo_type ((RankUnlockCondition|UsageUnlockCondition))>
    <!ELEMENT throwable ((RankUnlockCondition|UsageUnlockCondition))>
    <!ELEMENT aid ((RankUnlockCondition|UsageUnlockCondition))>
    <!ELEMENT melee_weapon ((RankUnlockCondition|UsageUnlockCondition))>
    <!ELEMENT bomb ((RankUnlockCondition|UsageUnlockCondition),bomb_special_effect*)>
    <!ELEMENT trap ((RankUnlockCondition|UsageUnlockCondition), trap_special_effect*)>
    <!ELEMENT other_item ((RankUnlockCondition|UsageUnlockCondition), other_item_special_effect*)>
    <!ELEMENT RankUnlockCondition EMPTY>
    <!ELEMENT UsageUnlockCondition EMPTY>
    <!ELEMENT damage_spec EMPTY>

    <!ELEMENT bomb_special_effect EMPTY>
    <!ELEMENT trap_special_effect EMPTY>
    <!ELEMENT other_item_special_effect EMPTY>





    <!-- ************ ATTRIBUTE SECTION ************ -->




    <!-- unlock condition attributes -->
    <!ATTLIST RankUnlockCondition requiredBloodlineRank CDATA #REQUIRED>
    <!ATTLIST UsageUnlockCondition requiredItemUnlockId IDREF #REQUIRED>
    <!ATTLIST UsageUnlockCondition usingItems IDREFS #REQUIRED>
    <!ATTLIST UsageUnlockCondition usageRequirement CDATA #REQUIRED>
    <!ATTLIST UsageUnlockCondition unit (XPPoints|timesUsed) #REQUIRED>



    <!-- projectile weapon attributes -->
    <!-- shared from hs item -->
    <!ATTLIST projectile_weapon id ID #REQUIRED>
    <!ATTLIST projectile_weapon name CDATA #REQUIRED>
    <!ATTLIST projectile_weapon price CDATA #REQUIRED>
    <!ATTLIST projectile_weapon melee_damage_light CDATA #REQUIRED>
    <!ATTLIST projectile_weapon melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST projectile_weapon item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!-- own attributes -->
    <!ATTLIST projectile_weapon slots_consumed (1|2|3) #REQUIRED>
    <!ATTLIST projectile_weapon scope (None|Small|Medium|Long) #REQUIRED>
    <!ATTLIST projectile_weapon has_silencer (yes|no) #REQUIRED>
    <!ATTLIST projectile_weapon action (Lever|Bolt|SingleAction|SemiAuto|Auto|BowString|BreakActionSingleBarrel|BreakActionDoubleBarrel|PumpAction|Other) #REQUIRED>
    <!ATTLIST projectile_weapon can_double_wield (yes|no) #REQUIRED>
    <!ATTLIST projectile_weapon fire_rate_per_minute CDATA #REQUIRED>
    <!ATTLIST projectile_weapon clip_size CDATA #REQUIRED>
    <!ATTLIST projectile_weapon ammo_types IDREFS #REQUIRED>
    <!ATTLIST projectile_weapon can_bear_multiple_ammo_types (yes|no) #REQUIRED>
    <!ATTLIST projectile_weapon melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST projectile_weapon melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>





    <!-- ammo attributes -->
    <!-- shared from hs item -->
    <!ATTLIST ammo_type id ID #REQUIRED>
    <!ATTLIST ammo_type name CDATA #REQUIRED>
    <!ATTLIST ammo_type price CDATA #REQUIRED>
    <!-- own attributes -->
    <!ATTLIST ammo_type ammo_supply CDATA #REQUIRED>
    <!ATTLIST ammo_type projectile_type (BulletShortAmmo|BulletMediumAmmo|BulletLongAmmo|Buckshot|Arrow|Special) #REQUIRED>
    <!ATTLIST ammo_type ammo_special_effect (Poisoning|ArmorPiercing|FullMetallJacket|Explosive|Incendiary|Bleeding|None) #REQUIRED>




    <!-- melee weapon attributes -->
    <!-- shared from hs item -->
    <!ATTLIST melee_weapon id ID #REQUIRED>
    <!ATTLIST melee_weapon name CDATA #REQUIRED>
    <!ATTLIST melee_weapon price CDATA #REQUIRED>
    <!ATTLIST melee_weapon melee_damage_light CDATA #REQUIRED>
    <!ATTLIST melee_weapon melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST melee_weapon item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!-- own attributes -->
    <!ATTLIST melee_weapon slots_consumed (1|2|3) #REQUIRED>
    <!ATTLIST melee_weapon melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST melee_weapon melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>



    <!-- throwable attributes -->
    <!-- shared from hs item -->
    <!ATTLIST throwable id ID #REQUIRED>
    <!ATTLIST throwable name CDATA #REQUIRED>
    <!ATTLIST throwable price CDATA #REQUIRED>
    <!ATTLIST throwable melee_damage_light CDATA #REQUIRED>
    <!ATTLIST throwable melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST throwable item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!-- own attributes -->
    <!ATTLIST throwable damage_on_impact CDATA #REQUIRED>
    <!ATTLIST throwable pack_size CDATA #REQUIRED>
    <!ATTLIST throwable sticks_to_objects (yes|no) #REQUIRED>
    <!ATTLIST throwable is_decoy (yes|no) #REQUIRED>
    <!ATTLIST throwable melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST throwable melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>


    <!-- bomb attributes -->
    <!-- shares from hs item -->
    <!ATTLIST bomb id ID #REQUIRED>
    <!ATTLIST bomb name CDATA #REQUIRED>
    <!ATTLIST bomb price CDATA #REQUIRED>
    <!ATTLIST bomb melee_damage_light CDATA #REQUIRED>
    <!ATTLIST bomb melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST bomb item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!-- shared from throwable -->
    <!ATTLIST bomb damage_on_impact CDATA #REQUIRED>
    <!ATTLIST bomb pack_size CDATA #REQUIRED>
    <!ATTLIST bomb sticks_to_objects (yes|no) #REQUIRED>
    <!ATTLIST bomb is_decoy (yes|no) #REQUIRED>
    <!-- own -->
    <!ATTLIST bomb cooking_time CDATA #REQUIRED>
    <!ATTLIST bomb impact_radius CDATA #REQUIRED>
    <!ATTLIST bomb aoe_damage CDATA #REQUIRED>
    <!ATTLIST bomb goes_off_under_water (yes|no) #REQUIRED>
    <!ATTLIST bomb melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST bomb melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>



    <!-- trap attributes -->
    <!-- shares from hs item -->
    <!ATTLIST trap id ID #REQUIRED>
    <!ATTLIST trap name CDATA #REQUIRED>
    <!ATTLIST trap price CDATA #REQUIRED>
    <!ATTLIST trap melee_damage_light CDATA #REQUIRED>
    <!ATTLIST trap melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST trap item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!-- own -->
    <!ATTLIST trap pack_size CDATA #REQUIRED>
    <!ATTLIST trap melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST trap melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>



    <!-- aid item attributes -->
    <!-- shares from hs item -->
    <!ATTLIST aid id ID #REQUIRED>
    <!ATTLIST aid name CDATA #REQUIRED>
    <!ATTLIST aid price CDATA #REQUIRED>
    <!ATTLIST aid melee_damage_light CDATA #REQUIRED>
    <!ATTLIST aid melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST aid item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!-- own -->
    <!ATTLIST aid health_restored CDATA #REQUIRED>
    <!ATTLIST aid effect_duration CDATA #REQUIRED>
    <!ATTLIST aid special_effect (PoisonImmunity|StaminaBoost|None) #REQUIRED>
    <!ATTLIST aid melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST aid melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST aid pack_size CDATA #REQUIRED>



    <!-- other item attributes -->
    <!-- shares from hs item -->
    <!ATTLIST other_item id ID #REQUIRED>
    <!ATTLIST other_item name CDATA #REQUIRED>
    <!ATTLIST other_item price CDATA #REQUIRED>
    <!ATTLIST other_item melee_damage_light CDATA #REQUIRED>
    <!ATTLIST other_item melee_damage_heavy CDATA #REQUIRED>
    <!ATTLIST other_item item_category (Ammo|MainWeapon|Consumable|Tool) #REQUIRED>
    <!ATTLIST other_item melee_damage_light_type (Blunt|Cut|Pierce) #REQUIRED>
    <!ATTLIST other_item melee_damage_heavy_type (Blunt|Cut|Pierce) #REQUIRED>


    <!-- bomb/trap/other_item special effect attributes -->
    <!ATTLIST bomb_special_effect effect_type (Blinding|Sharpnel|Bleeding|Poisoning|Incendiary) #REQUIRED>
    <!ATTLIST trap_special_effect effect_type (Poisoning|Bleeding|SlowDown|Incendiary) #REQUIRED>
    <!ATTLIST other_item_special_effect effect_type (Binocular|LightSource|Incendiary|AmmoSupply) #REQUIRED>


    <!-- damage spec attributes -->
    <!ATTLIST damage_spec weapon_id IDREF #REQUIRED>
    <!ATTLIST damage_spec ammo_id IDREF #REQUIRED>
    <!ATTLIST damage_spec damage CDATA #REQUIRED>
    <!ATTLIST damage_spec muzzle_velocity CDATA #REQUIRED>
    <!ATTLIST damage_spec effective_range CDATA #REQUIRED>

]>

<root>
    <items>
        <ammo>
            <ammo_type
                id="sparks_ammo_standard"
                name="Standard Sparks Ammo"
                price="0"
                ammo_supply="8"
                projectile_type="BulletLongAmmo"
                ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="27" />
            </ammo_type>
            <ammo_type
                    id="lebel_ammo_standard"
                    name="Standard Lebel 1886 Ammo"
                    price="0"
                    ammo_supply="7"
                    projectile_type="BulletLongAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="52" />
            </ammo_type>
            <ammo_type
                    id="martini_ammo_standard"
                    name="Martini-Henry IC1 Standard Ammo"
                    price="0"
                    ammo_supply="10"
                    projectile_type="BulletLongAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="16" />
            </ammo_type>
            <ammo_type
                    id="mosin_ammo_standard"
                    name="Standard Mosin-Nagant M1891 Ammo"
                    price="0"
                    ammo_supply="7"
                    projectile_type="BulletLongAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="72" />
            </ammo_type>
            <ammo_type
                    id="romero_ammo_standard"
                    name="Standard Romero 77 Ammo"
                    price="0"
                    ammo_supply="6"
                    projectile_type="Buckshot"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="1" />
            </ammo_type>
            <ammo_type
                    id="specter_ammo_standard"
                    name="Standard Specter 1882 Ammo"
                    price="0"
                    ammo_supply="7"
                    projectile_type="Buckshot"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="58" />
            </ammo_type>
            <!-- springfield family -->
            <ammo_type
                    id="springfield_ammo_standard"
                    name="Standard"
                    price="0"
                    ammo_supply="12"
                    projectile_type="BulletMediumAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="1" />
            </ammo_type>
            <ammo_type
                    id="springfield_ammo_dumdum"
                    name="Dumdum"
                    price="50"
                    ammo_supply="12"
                    projectile_type="BulletMediumAmmo"
                    ammo_special_effect="Bleeding"
            >
                <UsageUnlockCondition
                        requiredItemUnlockId="springfield_marksman"
                        usingItems="springfield springfield_marksman"
                        usageRequirement="750"
                        unit="XPPoints"/>
            </ammo_type>
            <ammo_type
                    id="springfield_ammo_explosive"
                    name="Explosive"
                    price="90"
                    ammo_supply="9"
                    projectile_type="BulletMediumAmmo"
                    ammo_special_effect="Explosive"
            >
                <UsageUnlockCondition
                        requiredItemUnlockId="springfield_obrez_deadeye"
                        usingItems="springfield springfield_marksman springfield_obrez springfield_obrez_bayonet springfield_obrez_deadeye"
                        usageRequirement="750"
                        unit="XPPoints"/>
            </ammo_type>
            <ammo_type
                    id="vetterli_ammo_standard"
                    name="Standard Vetterli 71 Ammo"
                    price="0"
                    ammo_supply="13"
                    projectile_type="BulletMediumAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="6" />
            </ammo_type>
            <ammo_type
                    id="terminus_ammo_standard"
                    name="Standard Winfield 1887 Terminus Ammo"
                    price="0"
                    ammo_supply="6"
                    projectile_type="BulletMediumAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="64" />
            </ammo_type>
            <!-- winfield family -->
            <ammo_type
                    id="winfield_ammo_standard"
                    name="Standard"
                    price="0"
                    ammo_supply="18"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="20" />
            </ammo_type>
            <ammo_type
                    id="winfield_ammo_incendiary"
                    name="Incendiary"
                    price="25"
                    ammo_supply="18"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="Incendiary"
            >
                <UsageUnlockCondition
                        requiredItemUnlockId="winfield_aperture"
                        usingItems="winfield winfield_aperture"
                        usageRequirement="750"
                        unit="XPPoints"/>
            </ammo_type>
            <ammo_type
                    id="winfield_ammo_high_velocity"
                    name="High Velocity"
                    price="75"
                    ammo_supply="18"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <UsageUnlockCondition
                        requiredItemUnlockId="winfield_talon"
                        usingItems="winfield winfield_aperture winfield_talon"
                        usageRequirement="750"
                        unit="XPPoints"/>
            </ammo_type>
            <ammo_type
                    id="winfield_ammo_fmj"
                    name="FMJ"
                    price="35"
                    ammo_supply="18"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="FullMetallJacket"
            >
                <UsageUnlockCondition
                        requiredItemUnlockId="winfield_swift"
                        usingItems="winfield winfield_aperture winfield_talon winfield_swift"
                        usageRequirement="750"
                        unit="XPPoints"/>
            </ammo_type>
            <ammo_type
                    id="bornheim_ammo_standard"
                    name="Standard Bornheim No. 3 Ammo"
                    price="0"
                    ammo_supply="8"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="30" />
            </ammo_type>
            <ammo_type
                    id="conversion_ammo_standard"
                    name="Standard Conversion Ammo"
                    price="0"
                    ammo_supply="12"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="22" />
            </ammo_type>
            <ammo_type
                    id="pax_ammo_standard"
                    name="Standard Ammo"
                    price="0"
                    ammo_supply="9"
                    projectile_type="BulletMediumAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="10" />
            </ammo_type>
            <ammo_type
                    id="dolch_ammo_standard"
                    name="Standard Ammo"
                    price="0"
                    ammo_supply="10"
                    projectile_type="Special"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="10" />
            </ammo_type>
            <ammo_type
                    id="hand_crossbow_ammo_standard"
                    name="Standard Ammo"
                    price="0"
                    ammo_supply="6"
                    projectile_type="Arrow"
                    ammo_special_effect="Bleeding"
            >
                <RankUnlockCondition requiredBloodlineRank="4" />
            </ammo_type>
            <ammo_type
                    id="lemat_ammo_standard"
                    name="Standard Ammo"
                    price="0"
                    ammo_supply="13"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="46" />
            </ammo_type>
            <ammo_type
                    id="nagant_ammo_standard"
                    name="Standard"
                    price="0"
                    ammo_supply="14"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="1" />
            </ammo_type>
            <ammo_type
                    id="officer_ammo_standard"
                    name="Standard Ammo"
                    price="0"
                    ammo_supply="10"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <RankUnlockCondition requiredBloodlineRank="1" />
            </ammo_type>
            <ammo_type
                    id="nagant_ammo_poison"
                    name="Poison"
                    price="35"
                    ammo_supply="14"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="Poisoning"
            >
                <UsageUnlockCondition requiredItemUnlockId="nagant_deadeye" usingItems="nagant nagant_precision nagant_silencer nagant_deadeye" usageRequirement="750" unit="XPPoints"/>
            </ammo_type>
            <ammo_type
                    id="nagant_ammo_high_velocity"
                    name="High Velocity"
                    price="75"
                    ammo_supply="14"
                    projectile_type="BulletShortAmmo"
                    ammo_special_effect="None"
            >
                <UsageUnlockCondition requiredItemUnlockId="nagant_ammo_poison" usingItems="nagant nagant_precision nagant_silencer nagant_deadeye" usageRequirement="750" unit="XPPoints"/>
            </ammo_type>
        </ammo>
        <projectile_weapons>
            <projectile_weapon
                id="sparks"
                name="Sparks LRR"
                price="130"
                melee_damage_light="27"
                melee_damage_heavy="54"
                slots_consumed="3"
                scope="None"
                has_silencer="no"
                action="SingleAction"
                can_double_wield="no"
                fire_rate_per_minute="38"
                clip_size="1"
                ammo_types="sparks_ammo_standard"
                item_category="MainWeapon"
                can_bear_multiple_ammo_types="no"
                melee_damage_light_type="Blunt"
                melee_damage_heavy_type="Blunt"
            >
                <RankUnlockCondition requiredBloodlineRank="27" />
            </projectile_weapon>
            <projectile_weapon
                    id="lebel"
                    name="Lebel 1886"
                    price="397"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="None"
                    has_silencer="no"
                    action="Bolt"
                    can_double_wield="no"
                    fire_rate_per_minute="34"
                    clip_size="10"
                    ammo_types="lebel_ammo_standard"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="no"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <RankUnlockCondition requiredBloodlineRank="52" />
            </projectile_weapon>
            <projectile_weapon
                    id="martini"
                    name="Martini-Henry IC1"
                    price="122"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="None"
                    has_silencer="no"
                    action="Lever"
                    can_double_wield="no"
                    fire_rate_per_minute="45"
                    clip_size="1"
                    ammo_types="martini_ammo_standard"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="yes"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <RankUnlockCondition requiredBloodlineRank="16" />
            </projectile_weapon>
            <projectile_weapon
                    id="mosin"
                    name="Mosin-Nagant M1891"
                    price="490"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="None"
                    has_silencer="no"
                    action="Bolt"
                    can_double_wield="no"
                    fire_rate_per_minute="34"
                    clip_size="5"
                    ammo_types="mosin_ammo_standard"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="no"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <RankUnlockCondition requiredBloodlineRank="72" />
            </projectile_weapon>
            <projectile_weapon
                    id="romero"
                    name="Romero 77"
                    price="34"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="None"
                    has_silencer="no"
                    action="BreakActionSingleBarrel"
                    can_double_wield="no"
                    fire_rate_per_minute="30"
                    clip_size="1"
                    ammo_types="romero_ammo_standard"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="yes"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <RankUnlockCondition requiredBloodlineRank="1" />
            </projectile_weapon>
            <projectile_weapon
                    id="specter"
                    name="Specter 1882 Bayonet"
                    price="188"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="None"
                    has_silencer="no"
                    action="PumpAction"
                    can_double_wield="no"
                    fire_rate_per_minute="30"
                    clip_size="5"
                    ammo_types="specter_ammo_standard"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="no"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Pierce"
            >
                <RankUnlockCondition requiredBloodlineRank="58" />
            </projectile_weapon>
            <!-- springfield family -->
            <projectile_weapon
                    id="springfield"
                    name="Springfield 1866"
                    price="38"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="None"
                    has_silencer="no"
                    action="SingleAction"
                    can_double_wield="no"
                    fire_rate_per_minute="42"
                    clip_size="1"
                    ammo_types="springfield_ammo_standard springfield_ammo_dumdum springfield_ammo_explosive"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="yes"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <RankUnlockCondition requiredBloodlineRank="1" />
            </projectile_weapon>
            <projectile_weapon
                    id="springfield_marksman"
                    name="Springfield 1866 Marksman"
                    price="73"
                    melee_damage_light="27"
                    melee_damage_heavy="54"
                    slots_consumed="3"
                    scope="Medium"
                    has_silencer="no"
                    action="SingleAction"
                    can_double_wield="no"
                    fire_rate_per_minute="42"
                    clip_size="1"
                    ammo_types="springfield_ammo_standard springfield_ammo_dumdum springfield_ammo_explosive"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="yes"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <UsageUnlockCondition requiredItemUnlockId="springfield" usingItems="springfield" usageRequirement="750" unit="XPPoints"/>
            </projectile_weapon>
            <projectile_weapon
                    id="springfield_obrez"
                    name="Springfield 1866 Compact"
                    price="33"
                    melee_damage_light="13"
                    melee_damage_heavy="31"
                    slots_consumed="2"
                    scope="None"
                    has_silencer="no"
                    action="SingleAction"
                    can_double_wield="no"
                    fire_rate_per_minute="42"
                    clip_size="1"
                    ammo_types="springfield_ammo_standard springfield_ammo_dumdum springfield_ammo_explosive"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="yes"
                    melee_damage_light_type="Blunt"
                    melee_damage_heavy_type="Blunt"
            >
                <UsageUnlockCondition requiredItemUnlockId="springfield_ammo_dumdum" usingItems="springfield springfield_marksman" usageRequirement="750" unit="XPPoints"/>
            </projectile_weapon>
            <projectile_weapon
                    id="springfield_obrez_bayonet"
                    name="Springfield 1866 Compact Striker"
                    price="56"
                    melee_damage_light="52"
                    melee_damage_heavy="105"
                    slots_consumed="2"
                    scope="None"
                    has_silencer="no"
                    action="SingleAction"
                    can_double_wield="no"
                    fire_rate_per_minute="42"
                    clip_size="1"
                    ammo_types="springfield_ammo_standard springfield_ammo_dumdum springfield_ammo_explosive"
                    item_category="MainWeapon"
                    can_bear_multiple_ammo_types="yes"
                    melee_damage_light_type="Cut"
                    melee_damage_heavy_type="Pierce"
            >
                <UsageUnlockCondition requiredItemUnlockId="springfield_obrez" usingItems="springfield springfield_marksman springfield_obrez" usageRequirement="750" unit="XPPoints"/>
            </projectile_weapon>
            <projectile_weapon
                    id="springfield_obrez_deadeye"
                    name="Springfield 1866 Compact Deadeye"
                    price="46"
                    melee_damage_light="13"
                    melee_damage_heavy="31"
                    slots_consumed="2"
                    scope="Small"
                    has_silencer="no"
                    action="SingleAction"
                    can_double_wield="no"
                    fire_rate_per_minute="42"
                    clip_size="1"